AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: PaySlice Transactional SMS Microservice (AWS-native SAM + Twilio)

Globals:
  Function:
    Runtime: python3.12
    Timeout: 30
    MemorySize: 256
    Architectures:
      - x86_64
    Environment:
      Variables:
        AWS_REGION: !Ref AWS::Region
        LOG_LEVEL: INFO
        TWILIO_SECRET_NAME: !Ref TwilioSecretName
    Tracing: Active

Parameters:
  StageName:
    Type: String
    Default: staging
    Description: Deployment stage (staging/prod)
  TwilioSecretName:
    Type: String
    Default: payslice/twilio/txn
    Description: Name of AWS Secrets Manager secret storing Twilio credentials
  ApprovedDelaySeconds:
    Type: Number
    Default: 120
    Description: Delay (in seconds) for “Approved” SMS messages
  IdempotencyTableName:
    Type: String
    Default: payslice-sms-idempotency
    Description: DynamoDB table name for idempotency (optional)

Resources:

  ### API Gateway
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref StageName
      CorsConfiguration:
        AllowMethods: [GET, POST, OPTIONS]
        AllowHeaders: [Content-Type, Authorization]
        AllowOrigins: ['*']

  ### SQS Queue for delayed “Approved” messages
  ApprovedQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 300
      DelaySeconds: !Ref ApprovedDelaySeconds
      MessageRetentionPeriod: 86400

  ### Dead-letter queue for failures
  DLQ:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600 # 14 days

  ### Idempotency Table (optional)
  IdempotencyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref IdempotencyTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: exp
        Enabled: true

  ### Lambda - /sms endpoint
  IngestFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: payslice-sms-ingest
      CodeUri: src/
      Handler: ingest.lambda_handler
      Environment:
        Variables:
          APPROVED_QUEUE_URL: !Ref ApprovedQueue
          APPROVED_DELAY_SECONDS: !Ref ApprovedDelaySeconds
          IDEMPOTENCY_TABLE: !Ref IdempotencyTableName
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action: secretsmanager:GetSecretValue
              Resource: "*"
            - Effect: Allow
              Action: sqs:SendMessage
              Resource: !GetAtt ApprovedQueue.Arn
            - Effect: Allow
              Action: dynamodb:PutItem
              Resource: !GetAtt IdempotencyTable.Arn
      Events:
        IngestApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /sms
            Method: POST

  ### Lambda - Worker for delayed “Approved” messages
  WorkerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: payslice-sms-worker
      CodeUri: src/
      Handler: worker.lambda_handler
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: "*"
            - Effect: Allow
              Action:
                - sqs:ReceiveMessage
                - sqs:DeleteMessage
                - sqs:GetQueueAttributes
              Resource: !GetAtt ApprovedQueue.Arn
      Events:
        SQSTrigger:
          Type: SQS
          Properties:
            Queue: !GetAtt ApprovedQueue.Arn
            BatchSize: 10
            Enabled: true

  ### Lambda - /twilio/status webhook
  StatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: payslice-sms-status
      CodeUri: src/
      Handler: status.lambda_handler
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        StatusApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /twilio/status
            Method: POST

  ### Lambda - /healthz and /version endpoints
  HealthFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: payslice-sms-health
      CodeUri: src/
      Handler: health.lambda_handler
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        HealthCheck:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /healthz
            Method: GET
        VersionCheck:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /version
            Method: GET

Outputs:
  ApiBaseUrl:
    Description: HTTPS base URL for PaySlice SMS API
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/"
  QueueUrl:
    Description: URL of the ApprovedQueue
    Value: !Ref ApprovedQueue
  IdempotencyTable:
    Description: DynamoDB table for idempotency (optional)
    Value: !Ref IdempotencyTableName
